version: '2'
services:
  db:
    env_file: .env
    image: mariadb:10.1
    expose:
      - "3306"
    volumes:
      - ./data/db:/var/lib/mysql
  presidedemosite:
    env_file: .env
    build: .
    links:
      - db:presidedb
    ports:
      - "80:8080"
    volumes:
      - ./data/uploads:/var/www/uploads
      - ./data/logs:/var/www/logs